# Generated by Django 6.0.6 on 2026-06-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_sociallinks_alter_about_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sociallinks",
            options={"verbose_name_plural": "SocialLinks"},
        ),
    ]
