# Generated by Django 6.0.6 on 2026-06-17 08:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_demoblog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DemoBlog",
        ),
        migrations.AlterField(
            model_name="blog",
            name="blog_body",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
    ]
